FROM python:3.9-slim-buster
ENV PYTHONUNBUFFERED=1
WORKDIR /code
RUN apt-get -y update
RUN apt-get -y install build-essential
COPY requirements_site.txt /code/
RUN pip install -r requirements_site.txt
COPY site/ /code/
EXPOSE 8000
CMD ["./manage.py", "runserver"]